language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
services:
  - mongodb
before_install: npm install -g grunt-cli bower
install:
  - npm install
  - npm install codecov.io
after_success: cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js
